### ISSUE TITLE
No serial connection to the Mega

### ISSUE THREAD

**Issue by tellblom** [seb821/espRFLinkMQTT#16]
Using a MEGA 2560 (proberbly a china clone) and the ESP01 When I have the ESP01 in teh programmer it works and it gets an IP address and I could connect to the web.
When connectiong it to the MEGA it seems like it does not go pass the initial serial connection. It gets no IP, and it seems like it just hangs.

Running latest: RFLink Gateway V1.1 - R48

Have I connected it wrong?: 
**ESP    //  Mega**
GND  //  GND
VCC   //  3.3V
RX     //  TX0 (1)
TX     //  RX0(0)

**Comment by seb821** [comment]
Not enough information (log, ...). Dev version may fix the issue.
