### ISSUE TITLE
Ota updates

### ISSUE THREAD

**Issue by VinceEatWorld** [seb821/espRFLinkMQTT#19]
Hi Seb,

You mention the possibility to do over-the-air updates in the readme, but I was wondering how to do this exactly. Which file is needed and is the current configuration saved?

Thanks!

**Comment by seb821** [comment]
For OTA, there are two options :
- From web interface in tab System > Tools >Load firmware > Firmware
- From Arduino IDE or Platformio
For configuration, it is unliked it will be saved. Indeed, new firmware most likely include new CONFIG_VERSION wich will reset configuration. So you should make notes.
