### ISSUE TITLE
Problème  compilation avec IDE Arduino

### ISSUE THREAD

**Issue by Pat5659** [seb821/espRFLinkMQTT#21]
Bonjour Seb821
Je  suis très interessé par votre projet pour l'intégrer dans ma domotique mais meme apres avoir suivi correctement le read.me,je ne parviens pas a compiler votre  derniere release avec Arduino  1.13 `sur  une Wemos d1 mini  avec cette erreur `exit status 1
'g_pcont' was not declared in this scope` le problème se situe sur esprflinkmqtt.ino aux lignes html 725,726,727 , je pense qu'il s'agit d'un souci de librairie,j'ai tenté également avec platformio mais sans résultat positif

Merci par avance pour votre aide

**Comment by seb821** [comment]
Cette fonction a été retirée depuis. Essayez avec la branche dev. Elle compile sans problème avec Arduio IDE et Platformio.
