### ISSUE TITLE
Invalid json on publish

### ISSUE THREAD

**Issue by HenJou** [seb821/espRFLinkMQTT#23]
Hi I tested the the espRFLinkMQTT and i tryed the latest dev one but I get an error on my DKW2012 Weather station on the json that is published to my mqtt server .  This is the json that is returned

{"TEMP":15.8,"HUM":48,"WINSP":0.0,"WINGS":0.0,"RAIN":5.4,"WINDIR":0010,"BAT":"OK"}

if I run this thru json validate at https://jsonlint.com/ I get thats WINDIR value that's not valid.

My Milight is working and also my other Temp sensors.

![image](https://user-images.githubusercontent.com/26525632/115458353-e7b7bc80-a225-11eb-94f7-b1d49a5f6d5b.png)

**Comment by HenJou** [comment]
What I got from rflink is that the WINDIR of the DKW2012 is a value from 0-15 and every 1 is 22.5 deg. so the 0010 above is then 10 * 22.5 = 225 degrees.  Hope this can help.

**Comment by seb821** [comment]
I have just pushed a fix on the dev branch to convert it to a proper integer (without the zeros before).
Though, I did not implement the multiplication by 22.5 as RFLink reference says it is an integer (though it "reflects" an angle).
Maybe you can test and revert whether it is ok.

**Comment by HenJou** [comment]
Thank seb821 I test the dev and i do get a valid json back and I got the value back to Home assistant with the following configuration.yaml under sensors: , so no need to add the conversion also.
  - platform: mqtt
    name: "DKW Wind Direction"
    state_topic: "rflink/DKW2012-weather"
    value_template: "{{ value_json['WINDIR'] *22.5  }}"
