### ISSUE TITLE
Provide bin.file

### ISSUE THREAD

**Issue by chapeau84** [seb821/espRFLinkMQTT#25]
Hi,

I love the idea of this project and i'm quite sure i will love it once i got it working.

Is it possible to provide a .bin file? 
It seems i can't get the web browser after loading the sketch into the nodemcu yet and don't know why.
My setup is is using the RFlink prints and nodeMCU of www.nodo-shop.nl.

Greetings

**Comment by seb821** [comment]
In [release v1.0](https://github.com/seb821/espRFLinkMQTT/releases/tag/v1.0), please try bin file ending by "rflink-wifi-board" which is enabling the watchdog of the Nodo shop board for nodeMCU.
